---
abstract: 'Flexible::Output::Printer permits users to print output in a way that is remiscent of other programming languages such as UNIX Shell, Ruby, and Lua. (Working on adding support for more languages.)'
author:
  - 'Alexej G. Magura <agm2819@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Flexible-Output-Printer
no_index:
  directory:
    - t
    - inc
requires: {}
version: v0.4.5
